### ISSUE TITLE
1.2 Data Preprocessing

### ISSUE THREAD

**Issue by MR-NBD** [MR-NBD/ML4N--Adversarial-Attacks-Polito-2023-24#2]
# Data exploration and preprocessing

As a preprocessing step, convert categorical features to numerical features, e.g., by means of a one-hot encoding, and apply a normalization to map all features between [0, 1]. Assign labels to the dataset
indicating the true loan attribution outcomes for supervised learning. Clearly define categories or classes representing loan approval or denial. Additionally, reserve 20% of the dataset for final testing and assessment of the robustness of the models.

**Comment by Distii** [comment]
Completato ma con forse qualche dettaglio in più che va aggiunto nel report
